// Seed script to populate initial data
// Run with: node scripts/seed-data.js

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb+srv://dbuser:Password%40123@cosmos-ecommerce.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000&appName=ecommerce-app';

const UserSchema = new mongoose.Schema({
  email: String,
  password: String,
  name: String,
  role: String,
}, { timestamps: true });

const CategorySchema = new mongoose.Schema({
  name: String,
  slug: String,
  description: String,
}, { timestamps: true });

const ProductSchema = new mongoose.Schema({
  name: String,
  description: String,
  price: Number,
  image: String,
  category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
  stock: Number,
  sku: String,
  slug: String,
  featured: Boolean,
}, { timestamps: true });

const User = mongoose.model('User', UserSchema);
const Category = mongoose.model('Category', CategorySchema);
const Product = mongoose.model('Product', ProductSchema);

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI, {
      dbName: 'ecommerce', // Specify database name
      retryWrites: false, // Cosmos DB requires retryWrites=false
      tls: true,
      authMechanism: 'SCRAM-SHA-256',
      maxIdleTimeMS: 120000,
      minPoolSize: 5,
      maxPoolSize: 20,
    });
    console.log('✅ Connected to Azure Cosmos DB (ecommerce database)');

    // Create admin user
    const adminPassword = await bcrypt.hash('admin123', 10);
    const admin = await User.findOneAndUpdate(
      { email: 'admin@example.com' },
      {
        email: 'admin@example.com',
        password: adminPassword,
        name: 'Admin User',
        role: 'admin',
      },
      { upsert: true, new: true }
    );
    console.log('Admin user created:', admin.email);

    // Create categories (covering major e-commerce domains)
    const categoryDefinitions = [
      {
        name: 'Electronics',
        slug: 'electronics',
        description: 'Latest gadgets, accessories, and smart tech',
      },
      {
        name: 'Fashion & Apparel',
        slug: 'fashion-apparel',
        description: 'Lifestyle clothing, footwear, and accessories',
      },
      {
        name: 'Home & Kitchen',
        slug: 'home-kitchen',
        description: 'Cookware, appliances, and smart home essentials',
      },
      {
        name: 'Beauty & Personal Care',
        slug: 'beauty-personal-care',
        description: 'Skincare, grooming, and personal hygiene',
      },
      {
        name: 'Sports & Outdoors',
        slug: 'sports-outdoors',
        description: 'Performance gear for indoor and outdoor workouts',
      },
      {
        name: 'Books',
        slug: 'books',
        description: 'Best-selling fiction, non-fiction, and learning',
      },
      {
        name: 'Toys & Games',
        slug: 'toys-games',
        description: 'STEM kits, board games, and kids favourites',
      },
      {
        name: 'Grocery & Gourmet',
        slug: 'grocery-gourmet',
        description: 'Pantry staples, gourmet treats, and beverages',
      },
    ];

    const categories = {};
    for (const definition of categoryDefinitions) {
      categories[definition.slug] = await Category.findOneAndUpdate(
        { slug: definition.slug },
        definition,
        { upsert: true, new: true }
      );
    }
    console.log('Categories created');

    // Create sample products across every primary retail category
    // Prices are in Indian Rupees (₹)
    const products = [
      // Electronics - 10+ items
      {
        name: '4K Ultra HD Smart TV',
        description: '65-inch Dolby Vision smart TV with Alexa and Google Assistant built-in.',
        price: 99999,
        image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=900',
        category: categories['electronics']._id,
        stock: 25,
        sku: 'ELEC-TV-001',
        slug: '4k-ultra-hd-smart-tv',
        featured: true,
      },
      {
        name: 'Noise Cancelling Earbuds Pro',
        description: 'True wireless earbuds with adaptive noise cancellation and 32-hour battery.',
        price: 19999,
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900',
        category: categories['electronics']._id,
        stock: 70,
        sku: 'ELEC-EB-002',
        slug: 'noise-cancelling-earbuds-pro',
        featured: true,
      },
      {
        name: 'Wireless Bluetooth Speaker',
        description: '360° sound with 20W output, waterproof design, and 12-hour battery life.',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=900',
        category: categories['electronics']._id,
        stock: 85,
        sku: 'ELEC-SPK-003',
        slug: 'wireless-bluetooth-speaker',
        featured: false,
      },
      {
        name: 'Smartphone 128GB',
        description: '6.7-inch AMOLED display, 108MP camera, 5000mAh battery, 5G ready.',
        price: 24999,
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900',
        category: categories['electronics']._id,
        stock: 50,
        sku: 'ELEC-PHONE-004',
        slug: 'smartphone-128gb',
        featured: true,
      },
      {
        name: 'Gaming Laptop 16GB RAM',
        description: '15.6-inch FHD display, RTX 3060, Intel i7, 512GB SSD, RGB keyboard.',
        price: 89999,
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=900',
        category: categories['electronics']._id,
        stock: 30,
        sku: 'ELEC-LAP-005',
        slug: 'gaming-laptop-16gb-ram',
        featured: true,
      },
      {
        name: 'Smart Watch Pro',
        description: '1.4-inch AMOLED display, heart rate monitor, GPS, 7-day battery, water resistant.',
        price: 12999,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900',
        category: categories['electronics']._id,
        stock: 60,
        sku: 'ELEC-WATCH-006',
        slug: 'smart-watch-pro',
        featured: false,
      },
      {
        name: '4K Action Camera',
        description: 'Waterproof action camera with 4K video, image stabilization, and WiFi.',
        price: 14999,
        image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=900',
        category: categories['electronics']._id,
        stock: 45,
        sku: 'ELEC-CAM-007',
        slug: '4k-action-camera',
        featured: false,
      },
      {
        name: 'Mechanical Keyboard RGB',
        description: 'Full-size mechanical keyboard with RGB backlight, Cherry MX switches.',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900',
        category: categories['electronics']._id,
        stock: 75,
        sku: 'ELEC-KB-008',
        slug: 'mechanical-keyboard-rgb',
        featured: false,
      },
      {
        name: 'Wireless Mouse Ergonomic',
        description: 'Ergonomic wireless mouse with 2.4GHz connectivity, 1600 DPI, 18-month battery.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=900',
        category: categories['electronics']._id,
        stock: 100,
        sku: 'ELEC-MOUSE-009',
        slug: 'wireless-mouse-ergonomic',
        featured: false,
      },
      {
        name: 'Tablet 10.1 inch',
        description: '10.1-inch HD display, 64GB storage, 8MP camera, Android 12, 6000mAh battery.',
        price: 17999,
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=900',
        category: categories['electronics']._id,
        stock: 40,
        sku: 'ELEC-TAB-010',
        slug: 'tablet-10-1-inch',
        featured: false,
      },
      {
        name: 'Portable Power Bank 20000mAh',
        description: 'Fast charging power bank with USB-C and wireless charging, LED display.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1609091839311-d5365f5c3566?w=900',
        category: categories['electronics']._id,
        stock: 90,
        sku: 'ELEC-PB-011',
        slug: 'portable-power-bank-20000mah',
        featured: false,
      },
      {
        name: 'Smart Home Security Camera',
        description: '1080p HD security camera with night vision, motion detection, and mobile app.',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900',
        category: categories['electronics']._id,
        stock: 55,
        sku: 'ELEC-CAM-012',
        slug: 'smart-home-security-camera',
        featured: false,
      },
      // Fashion & Apparel - 10+ items
      {
        name: 'Merino Wool Hoodie',
        description: 'Premium athleisure zip hoodie made with breathable Merino wool.',
        price: 10999,
        image: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=900',
        category: categories['fashion-apparel']._id,
        stock: 120,
        sku: 'FASH-HOOD-001',
        slug: 'merino-wool-hoodie',
        featured: false,
      },
      {
        name: 'Statement Leather Tote',
        description: 'Handcrafted full-grain leather tote bag with magnetic closure.',
        price: 23999,
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900',
        category: categories['fashion-apparel']._id,
        stock: 60,
        sku: 'FASH-BAG-002',
        slug: 'statement-leather-tote',
        featured: true,
      },
      {
        name: 'Classic Denim Jacket',
        description: 'Vintage-style denim jacket with button closure and chest pockets.',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900',
        category: categories['fashion-apparel']._id,
        stock: 80,
        sku: 'FASH-JKT-003',
        slug: 'classic-denim-jacket',
        featured: false,
      },
      {
        name: 'Cotton T-Shirt Pack',
        description: 'Pack of 3 premium cotton t-shirts in assorted colors, comfortable fit.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900',
        category: categories['fashion-apparel']._id,
        stock: 150,
        sku: 'FASH-TS-004',
        slug: 'cotton-t-shirt-pack',
        featured: false,
      },
      {
        name: 'Sneakers Running Shoes',
        description: 'Lightweight running shoes with cushioned sole and breathable mesh upper.',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900',
        category: categories['fashion-apparel']._id,
        stock: 95,
        sku: 'FASH-SHOE-005',
        slug: 'sneakers-running-shoes',
        featured: true,
      },
      {
        name: 'Leather Belt Genuine',
        description: 'Genuine leather belt with adjustable buckle, classic design.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=900',
        category: categories['fashion-apparel']._id,
        stock: 70,
        sku: 'FASH-BELT-006',
        slug: 'leather-belt-genuine',
        featured: false,
      },
      {
        name: 'Wool Winter Scarf',
        description: 'Soft wool scarf in plaid pattern, perfect for winter season.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=900',
        category: categories['fashion-apparel']._id,
        stock: 110,
        sku: 'FASH-SCARF-007',
        slug: 'wool-winter-scarf',
        featured: false,
      },
      {
        name: 'Designer Sunglasses',
        description: 'UV protection sunglasses with polarized lenses and stylish frame.',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900',
        category: categories['fashion-apparel']._id,
        stock: 65,
        sku: 'FASH-SUN-008',
        slug: 'designer-sunglasses',
        featured: false,
      },
      {
        name: 'Casual Chinos Pants',
        description: 'Comfortable chinos pants in multiple colors, perfect for casual wear.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=900',
        category: categories['fashion-apparel']._id,
        stock: 85,
        sku: 'FASH-PANT-009',
        slug: 'casual-chinos-pants',
        featured: false,
      },
      {
        name: 'Formal Dress Shirt',
        description: 'Classic formal dress shirt with button-down collar, wrinkle-free fabric.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1594938291221-94f18cbb8b8a?w=900',
        category: categories['fashion-apparel']._id,
        stock: 100,
        sku: 'FASH-SHIRT-010',
        slug: 'formal-dress-shirt',
        featured: false,
      },
      {
        name: 'Backpack Laptop 15 inch',
        description: 'Durable laptop backpack with padded compartment, USB charging port.',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900',
        category: categories['fashion-apparel']._id,
        stock: 75,
        sku: 'FASH-BP-011',
        slug: 'backpack-laptop-15-inch',
        featured: false,
      },
      {
        name: 'Athletic Shorts',
        description: 'Moisture-wicking athletic shorts with elastic waistband and side pockets.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=900',
        category: categories['fashion-apparel']._id,
        stock: 130,
        sku: 'FASH-SHORT-012',
        slug: 'athletic-shorts',
        featured: false,
      },
      // Home & Kitchen - 10+ items
      {
        name: 'Smart Air Fryer Max',
        description: '5.5L digital air fryer with app control and 8 preset cooking modes.',
        price: 14999,
        image: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=900',
        category: categories['home-kitchen']._id,
        stock: 80,
        sku: 'HOME-AF-001',
        slug: 'smart-air-fryer-max',
        featured: true,
      },
      {
        name: 'Organic Memory Foam Pillow',
        description: 'Cooling gel-infused memory foam pillow with bamboo cover.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=900',
        category: categories['home-kitchen']._id,
        stock: 150,
        sku: 'HOME-PIL-002',
        slug: 'organic-memory-foam-pillow',
        featured: false,
      },
      {
        name: 'Non-Stick Cookware Set',
        description: '10-piece non-stick cookware set with glass lids and ergonomic handles.',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=900',
        category: categories['home-kitchen']._id,
        stock: 60,
        sku: 'HOME-COOK-003',
        slug: 'non-stick-cookware-set',
        featured: true,
      },
      {
        name: 'Coffee Maker Drip',
        description: '12-cup programmable coffee maker with auto shut-off and reusable filter.',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1517668808824-d4c0c42187a3?w=900',
        category: categories['home-kitchen']._id,
        stock: 70,
        sku: 'HOME-CM-004',
        slug: 'coffee-maker-drip',
        featured: false,
      },
      {
        name: 'Stand Mixer 5QT',
        description: '5-quart stand mixer with 10-speed control and multiple attachments.',
        price: 19999,
        image: 'https://images.unsplash.com/photo-1606914469633-bd39294ba5a6?w=900',
        category: categories['home-kitchen']._id,
        stock: 35,
        sku: 'HOME-MIX-005',
        slug: 'stand-mixer-5qt',
        featured: true,
      },
      {
        name: 'Bedding Set Queen',
        description: '4-piece cotton bedding set with pillowcases, fitted sheet, and duvet cover.',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=900',
        category: categories['home-kitchen']._id,
        stock: 90,
        sku: 'HOME-BED-006',
        slug: 'bedding-set-queen',
        featured: false,
      },
      {
        name: 'Vacuum Cleaner Robot',
        description: 'Smart robot vacuum with app control, auto-docking, and mapping technology.',
        price: 24999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900',
        category: categories['home-kitchen']._id,
        stock: 45,
        sku: 'HOME-VAC-007',
        slug: 'vacuum-cleaner-robot',
        featured: true,
      },
      {
        name: 'Kitchen Knife Set',
        description: '6-piece stainless steel knife set with wooden block and sharpener.',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1594736797933-d0c2d0e0c5e1?w=900',
        category: categories['home-kitchen']._id,
        stock: 85,
        sku: 'HOME-KNIFE-008',
        slug: 'kitchen-knife-set',
        featured: false,
      },
      {
        name: 'Table Lamp LED',
        description: 'Modern LED table lamp with touch control and adjustable brightness.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900',
        category: categories['home-kitchen']._id,
        stock: 100,
        sku: 'HOME-LAMP-009',
        slug: 'table-lamp-led',
        featured: false,
      },
      {
        name: 'Bath Towel Set',
        description: 'Set of 4 premium cotton bath towels, soft and highly absorbent.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1584433144859-1fc3ab64a957?w=900',
        category: categories['home-kitchen']._id,
        stock: 120,
        sku: 'HOME-TOWEL-010',
        slug: 'bath-towel-set',
        featured: false,
      },
      {
        name: 'Storage Baskets Set',
        description: 'Set of 3 woven storage baskets for home organization, various sizes.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900',
        category: categories['home-kitchen']._id,
        stock: 110,
        sku: 'HOME-BASK-011',
        slug: 'storage-baskets-set',
        featured: false,
      },
      {
        name: 'Wall Clock Modern',
        description: 'Large modern wall clock with silent movement and minimalist design.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=900',
        category: categories['home-kitchen']._id,
        stock: 65,
        sku: 'HOME-CLOCK-012',
        slug: 'wall-clock-modern',
        featured: false,
      },
      // Beauty & Personal Care - 10+ items
      {
        name: 'Vitamin C Glow Kit',
        description: 'Dermatologist-tested Vitamin C serum + moisturizer combo.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 90,
        sku: 'BEAUTY-VC-001',
        slug: 'vitamin-c-glow-kit',
        featured: true,
      },
      {
        name: 'Luxury Grooming Essentials',
        description: 'Five-piece grooming set with sandalwood oil and beard serum.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 110,
        sku: 'BEAUTY-GROOM-002',
        slug: 'luxury-grooming-essentials',
        featured: false,
      },
      {
        name: 'Hair Dryer Professional',
        description: 'Ionic hair dryer with 1875W power, multiple heat settings, and concentrator.',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 75,
        sku: 'BEAUTY-DRY-003',
        slug: 'hair-dryer-professional',
        featured: false,
      },
      {
        name: 'Face Cleanser Gel',
        description: 'Gentle gel cleanser for all skin types, removes makeup and impurities.',
        price: 599,
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 140,
        sku: 'BEAUTY-CLEAN-004',
        slug: 'face-cleanser-gel',
        featured: false,
      },
      {
        name: 'Sunscreen SPF 50',
        description: 'Broad spectrum SPF 50 sunscreen, water-resistant, non-greasy formula.',
        price: 899,
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 125,
        sku: 'BEAUTY-SUN-005',
        slug: 'sunscreen-spf-50',
        featured: false,
      },
      {
        name: 'Electric Shaver Men',
        description: 'Cordless electric shaver with 3 rotary heads and wet/dry use.',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 60,
        sku: 'BEAUTY-SHAVE-006',
        slug: 'electric-shaver-men',
        featured: true,
      },
      {
        name: 'Lipstick Set 6 Colors',
        description: 'Set of 6 long-lasting lipsticks in trending shades, matte finish.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 95,
        sku: 'BEAUTY-LIP-007',
        slug: 'lipstick-set-6-colors',
        featured: false,
      },
      {
        name: 'Perfume Eau de Toilette',
        description: '100ml premium fragrance with floral and woody notes, long-lasting.',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 80,
        sku: 'BEAUTY-PERF-008',
        slug: 'perfume-eau-de-toilette',
        featured: true,
      },
      {
        name: 'Hair Serum Argan Oil',
        description: '100% pure argan oil hair serum for frizz control and shine.',
        price: 799,
        image: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 115,
        sku: 'BEAUTY-SERUM-009',
        slug: 'hair-serum-argan-oil',
        featured: false,
      },
      {
        name: 'Toothbrush Electric',
        description: 'Rechargeable electric toothbrush with 3 cleaning modes and timer.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1607613009820-a29f7aaf34d0?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 100,
        sku: 'BEAUTY-BRUSH-010',
        slug: 'toothbrush-electric',
        featured: false,
      },
      {
        name: 'Face Mask Sheet Pack',
        description: 'Pack of 10 hydrating face mask sheets with hyaluronic acid.',
        price: 999,
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 130,
        sku: 'BEAUTY-MASK-011',
        slug: 'face-mask-sheet-pack',
        featured: false,
      },
      {
        name: 'Nail Polish Set 12 Colors',
        description: 'Set of 12 nail polish bottles in various shades, quick-dry formula.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=900',
        category: categories['beauty-personal-care']._id,
        stock: 105,
        sku: 'BEAUTY-NAIL-012',
        slug: 'nail-polish-set-12-colors',
        featured: false,
      },
      // Sports & Outdoors - 10+ items
      {
        name: 'CarbonX Running Shoes',
        description: 'Responsive carbon-plated running shoes for marathon training.',
        price: 8999,
        image: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?w=900',
        category: categories['sports-outdoors']._id,
        stock: 95,
        sku: 'SPORT-SHOE-001',
        slug: 'carbonx-running-shoes',
        featured: true,
      },
      {
        name: 'Adjustable Smart Dumbbell Set',
        description: 'Pair of 25kg adjustable dumbbells with Bluetooth rep tracking.',
        price: 14999,
        image: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=900',
        category: categories['sports-outdoors']._id,
        stock: 40,
        sku: 'SPORT-DUMB-002',
        slug: 'adjustable-smart-dumbbell-set',
        featured: false,
      },
      {
        name: 'Yoga Mat Premium',
        description: 'Extra thick non-slip yoga mat with carrying strap, eco-friendly material.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=900',
        category: categories['sports-outdoors']._id,
        stock: 120,
        sku: 'SPORT-YOGA-003',
        slug: 'yoga-mat-premium',
        featured: false,
      },
      {
        name: 'Fitness Tracker Band',
        description: 'Activity tracker with heart rate monitor, sleep tracking, and 7-day battery.',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1579586337278-3befd40f17ca?w=900',
        category: categories['sports-outdoors']._id,
        stock: 85,
        sku: 'SPORT-TRACK-004',
        slug: 'fitness-tracker-band',
        featured: true,
      },
      {
        name: 'Basketball Official Size',
        description: 'Official size basketball with composite leather cover, indoor/outdoor use.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=900',
        category: categories['sports-outdoors']._id,
        stock: 70,
        sku: 'SPORT-BALL-005',
        slug: 'basketball-official-size',
        featured: false,
      },
      {
        name: 'Resistance Bands Set',
        description: 'Set of 5 resistance bands with different resistance levels and door anchor.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=900',
        category: categories['sports-outdoors']._id,
        stock: 110,
        sku: 'SPORT-BAND-006',
        slug: 'resistance-bands-set',
        featured: false,
      },
      {
        name: 'Cycling Helmet Safety',
        description: 'Lightweight cycling helmet with ventilation, adjustable fit, and safety certification.',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900',
        category: categories['sports-outdoors']._id,
        stock: 65,
        sku: 'SPORT-HELM-007',
        slug: 'cycling-helmet-safety',
        featured: false,
      },
      {
        name: 'Tennis Racket Pro',
        description: 'Professional tennis racket with graphite frame and pre-strung strings.',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1622163642999-9584e0f0ed82?w=900',
        category: categories['sports-outdoors']._id,
        stock: 50,
        sku: 'SPORT-RACK-008',
        slug: 'tennis-racket-pro',
        featured: false,
      },
      {
        name: 'Water Bottle Insulated',
        description: '1L stainless steel insulated water bottle, keeps drinks cold for 24 hours.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=900',
        category: categories['sports-outdoors']._id,
        stock: 135,
        sku: 'SPORT-BOTTLE-009',
        slug: 'water-bottle-insulated',
        featured: false,
      },
      {
        name: 'Gym Bag Sports',
        description: 'Large capacity gym bag with separate shoe compartment and water bottle holder.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900',
        category: categories['sports-outdoors']._id,
        stock: 90,
        sku: 'SPORT-BAG-010',
        slug: 'gym-bag-sports',
        featured: false,
      },
      {
        name: 'Jump Rope Adjustable',
        description: 'Adjustable length jump rope with weighted handles and tangle-free design.',
        price: 599,
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=900',
        category: categories['sports-outdoors']._id,
        stock: 150,
        sku: 'SPORT-ROPE-011',
        slug: 'jump-rope-adjustable',
        featured: false,
      },
      {
        name: 'Camping Tent 4 Person',
        description: '4-person camping tent with rainfly, easy setup, and carry bag.',
        price: 8999,
        image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=900',
        category: categories['sports-outdoors']._id,
        stock: 35,
        sku: 'SPORT-TENT-012',
        slug: 'camping-tent-4-person',
        featured: true,
      },
      // Books - 10+ items
      {
        name: 'Interactive Story Book Collection',
        description: 'Box set with 5 augmented reality story books for kids aged 5-9.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=900',
        category: categories['books']._id,
        stock: 85,
        sku: 'BOOKS-AR-001',
        slug: 'interactive-story-book-collection',
        featured: false,
      },
      {
        name: 'The Great Novel Hardcover',
        description: 'Bestselling fiction novel, hardcover edition with beautiful cover design.',
        price: 599,
        image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=900',
        category: categories['books']._id,
        stock: 100,
        sku: 'BOOKS-NOV-002',
        slug: 'the-great-novel-hardcover',
        featured: true,
      },
      {
        name: 'Self-Help Guide Success',
        description: 'Complete guide to personal development and achieving your goals.',
        price: 499,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
        category: categories['books']._id,
        stock: 120,
        sku: 'BOOKS-SELF-003',
        slug: 'self-help-guide-success',
        featured: false,
      },
      {
        name: 'Cookbook Recipes Collection',
        description: '500+ recipes from around the world with beautiful food photography.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=900',
        category: categories['books']._id,
        stock: 75,
        sku: 'BOOKS-COOK-004',
        slug: 'cookbook-recipes-collection',
        featured: true,
      },
      {
        name: 'Science Encyclopedia Kids',
        description: 'Illustrated science encyclopedia for children, 500+ pages of knowledge.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
        category: categories['books']._id,
        stock: 90,
        sku: 'BOOKS-SCI-005',
        slug: 'science-encyclopedia-kids',
        featured: false,
      },
      {
        name: 'Mystery Thriller Paperback',
        description: 'Gripping mystery thriller with unexpected twists and turns.',
        price: 399,
        image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=900',
        category: categories['books']._id,
        stock: 110,
        sku: 'BOOKS-THR-006',
        slug: 'mystery-thriller-paperback',
        featured: false,
      },
      {
        name: 'Programming Guide Python',
        description: 'Complete Python programming guide for beginners to advanced developers.',
        price: 899,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
        category: categories['books']._id,
        stock: 95,
        sku: 'BOOKS-PYTH-007',
        slug: 'programming-guide-python',
        featured: true,
      },
      {
        name: 'History World Events',
        description: 'Comprehensive history book covering major world events and civilizations.',
        price: 1099,
        image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=900',
        category: categories['books']._id,
        stock: 80,
        sku: 'BOOKS-HIST-008',
        slug: 'history-world-events',
        featured: false,
      },
      {
        name: 'Poetry Collection Modern',
        description: 'Collection of modern poetry from contemporary poets around the world.',
        price: 599,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
        category: categories['books']._id,
        stock: 105,
        sku: 'BOOKS-POET-009',
        slug: 'poetry-collection-modern',
        featured: false,
      },
      {
        name: 'Business Strategy Book',
        description: 'Essential guide to business strategy and entrepreneurship.',
        price: 799,
        image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=900',
        category: categories['books']._id,
        stock: 85,
        sku: 'BOOKS-BUS-010',
        slug: 'business-strategy-book',
        featured: false,
      },
      {
        name: 'Art Photography Coffee Table',
        description: 'Stunning coffee table book featuring world-class photography and art.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
        category: categories['books']._id,
        stock: 60,
        sku: 'BOOKS-ART-011',
        slug: 'art-photography-coffee-table',
        featured: true,
      },
      {
        name: 'Children Storybook Set',
        description: 'Set of 10 illustrated children storybooks with moral lessons.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=900',
        category: categories['books']._id,
        stock: 115,
        sku: 'BOOKS-KIDS-012',
        slug: 'children-storybook-set',
        featured: false,
      },
      // Toys & Games - 10+ items
      {
        name: 'STEM Robotics Starter Kit',
        description: '12-in-1 programmable robotics kit compatible with Scratch.',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=900',
        category: categories['toys-games']._id,
        stock: 65,
        sku: 'TOYS-ROBO-001',
        slug: 'stem-robotics-starter-kit',
        featured: true,
      },
      {
        name: 'Board Game Strategy',
        description: 'Award-winning strategy board game for 2-4 players, ages 10+.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=900',
        category: categories['toys-games']._id,
        stock: 80,
        sku: 'TOYS-BOARD-002',
        slug: 'board-game-strategy',
        featured: false,
      },
      {
        name: 'Building Blocks Set',
        description: '500-piece building blocks set with various shapes and colors.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900',
        category: categories['toys-games']._id,
        stock: 100,
        sku: 'TOYS-BLOCK-003',
        slug: 'building-blocks-set',
        featured: false,
      },
      {
        name: 'Remote Control Car',
        description: '1:14 scale remote control car with 2.4GHz controller and LED lights.',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900',
        category: categories['toys-games']._id,
        stock: 70,
        sku: 'TOYS-RC-004',
        slug: 'remote-control-car',
        featured: true,
      },
      {
        name: 'Puzzle 1000 Pieces',
        description: '1000-piece jigsaw puzzle with beautiful landscape image.',
        price: 899,
        image: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=900',
        category: categories['toys-games']._id,
        stock: 90,
        sku: 'TOYS-PUZZ-005',
        slug: 'puzzle-1000-pieces',
        featured: false,
      },
      {
        name: 'Action Figure Set',
        description: 'Set of 5 detailed action figures with accessories and display stand.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900',
        category: categories['toys-games']._id,
        stock: 85,
        sku: 'TOYS-FIG-006',
        slug: 'action-figure-set',
        featured: false,
      },
      {
        name: 'Musical Keyboard Kids',
        description: '37-key electronic keyboard with built-in songs and learning mode.',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=900',
        category: categories['toys-games']._id,
        stock: 55,
        sku: 'TOYS-KEY-007',
        slug: 'musical-keyboard-kids',
        featured: false,
      },
      {
        name: 'Doll House 3 Story',
        description: '3-story doll house with furniture set and accessories included.',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=900',
        category: categories['toys-games']._id,
        stock: 45,
        sku: 'TOYS-DOLL-008',
        slug: 'doll-house-3-story',
        featured: true,
      },
      {
        name: 'Card Game Family',
        description: 'Fun family card game for 3-8 players, quick rounds and easy to learn.',
        price: 499,
        image: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=900',
        category: categories['toys-games']._id,
        stock: 125,
        sku: 'TOYS-CARD-009',
        slug: 'card-game-family',
        featured: false,
      },
      {
        name: 'Science Experiment Kit',
        description: '50+ science experiments kit with lab equipment and instruction manual.',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=900',
        category: categories['toys-games']._id,
        stock: 75,
        sku: 'TOYS-SCI-010',
        slug: 'science-experiment-kit',
        featured: false,
      },
      {
        name: 'Art Supplies Set',
        description: 'Complete art supplies set with paints, brushes, canvas, and palette.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=900',
        category: categories['toys-games']._id,
        stock: 95,
        sku: 'TOYS-ART-011',
        slug: 'art-supplies-set',
        featured: false,
      },
      {
        name: 'Outdoor Play Set',
        description: 'Outdoor play set with slide, swing, and climbing features for kids.',
        price: 19999,
        image: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=900',
        category: categories['toys-games']._id,
        stock: 25,
        sku: 'TOYS-OUT-012',
        slug: 'outdoor-play-set',
        featured: true,
      },
      // Grocery & Gourmet - 10+ items
      {
        name: 'Gourmet Arabica Coffee Beans',
        description: 'Single-origin medium roast beans sourced from Colombia.',
        price: 999,
        image: 'https://images.unsplash.com/photo-1459257868276-5e65389e2722?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 130,
        sku: 'GROC-COFF-001',
        slug: 'gourmet-arabica-coffee-beans',
        featured: true,
      },
      {
        name: 'Artisanal Granola Variety Pack',
        description: 'Gluten-free breakfast granola with berries, cacao, and nuts.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 140,
        sku: 'GROC-GRAN-002',
        slug: 'artisanal-granola-variety-pack',
        featured: false,
      },
      {
        name: 'Organic Honey Raw',
        description: '100% pure raw organic honey, unfiltered and unpasteurized.',
        price: 799,
        image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 120,
        sku: 'GROC-HONEY-003',
        slug: 'organic-honey-raw',
        featured: false,
      },
      {
        name: 'Extra Virgin Olive Oil',
        description: 'Premium extra virgin olive oil, cold-pressed, 500ml bottle.',
        price: 899,
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 110,
        sku: 'GROC-OIL-004',
        slug: 'extra-virgin-olive-oil',
        featured: true,
      },
      {
        name: 'Dark Chocolate Assorted',
        description: 'Premium dark chocolate assortment, 70% cocoa, gift box.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1606312619070-d48b4cbc6b3c?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 100,
        sku: 'GROC-CHOC-005',
        slug: 'dark-chocolate-assorted',
        featured: false,
      },
      {
        name: 'Gourmet Tea Collection',
        description: 'Premium tea collection with 10 varieties including green, black, and herbal.',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 95,
        sku: 'GROC-TEA-006',
        slug: 'gourmet-tea-collection',
        featured: false,
      },
      {
        name: 'Organic Pasta Set',
        description: 'Set of 5 organic pasta varieties including penne, spaghetti, and fusilli.',
        price: 699,
        image: 'https://images.unsplash.com/photo-1551462147-5e923f53f283?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 125,
        sku: 'GROC-PASTA-007',
        slug: 'organic-pasta-set',
        featured: false,
      },
      {
        name: 'Spice Collection Premium',
        description: 'Premium spice collection with 15 essential spices in glass jars.',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 85,
        sku: 'GROC-SPICE-008',
        slug: 'spice-collection-premium',
        featured: true,
      },
      {
        name: 'Organic Quinoa 1kg',
        description: 'Premium organic quinoa, high protein, gluten-free, 1kg pack.',
        price: 599,
        image: 'https://images.unsplash.com/photo-1606312619070-d48b4cbc6b3c?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 115,
        sku: 'GROC-QUIN-009',
        slug: 'organic-quinoa-1kg',
        featured: false,
      },
      {
        name: 'Gourmet Cheese Selection',
        description: 'Assorted gourmet cheese selection with 5 varieties, perfect for platters.',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 70,
        sku: 'GROC-CHEESE-010',
        slug: 'gourmet-cheese-selection',
        featured: false,
      },
      {
        name: 'Premium Nuts Mix',
        description: 'Premium mixed nuts including almonds, cashews, walnuts, and pistachios.',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 105,
        sku: 'GROC-NUTS-011',
        slug: 'premium-nuts-mix',
        featured: false,
      },
      {
        name: 'Artisan Bread Mix',
        description: 'Ready-to-bake artisan bread mix with sourdough starter and instructions.',
        price: 499,
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900',
        category: categories['grocery-gourmet']._id,
        stock: 135,
        sku: 'GROC-BREAD-012',
        slug: 'artisan-bread-mix',
        featured: false,
      },
    ];

    for (const productData of products) {
      await Product.findOneAndUpdate(
        { sku: productData.sku },
        productData,
        { upsert: true, new: true }
      );
    }

    console.log('Products created');
    console.log('Seed data completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
}

seed();

